name: Build exampl LaTeX paper for eloop 2025
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: paper.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        id: upload-artifact-step
        with:
          name: PDF
          path: paper.pdf
